---
title: "Examen parcial"
subtitle: "Simulación"
author:
    name: Carlos Lezama [181121](https://celj.mx/)
    affiliation: Otoño 2021 | [ITAM](https://www.itam.mx/) | [EST 24107](https://github.com/celj/simulation-fall-2021)
date: "Lunes, 22 de noviembre de 2021"
output: 
    html_document:
        self_contained: true
        theme: flatly
        highlight: pygments
        code_folding: show
        toc: yes
        toc_depth: 4
        toc_float: yes
        css: css/preamble.css
        includes:
          in_header: "header.html"
always_allow_html: true
urlcolor: blue
sansfont: Fira Sans
monofont: Fira Code
---

```{r setup, include=FALSE}
library(rmarkdown)
library(tidyverse)
options(digits = 2)

knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE,
  fig.align = "center",
  fig.width = 9,
  fig.height = 6,
  cache = TRUE,
  dpi = 300
)

theme_set(theme_linedraw())

sin_lineas <- theme(panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank())

sin_leyenda <- theme(legend.position = "none")

sin_ejes <- theme(axis.ticks = element_blank(),
                  axis.text = element_blank())
```

# Problema 1

Dada una matriz $4 \times 4$ de variables aleatorias Bernoulli denotada por $\displaystyle \left[X_{ij}\right]$, sean $N(X)$ el número total de éxitos en $X$ y $D(X)$ el total de vecinos (horizontales o verticales) de dichos éxitos que difieren. Nótese que, si se escriben los elementos de $X$ en un vector $V$, existe una matriz $\displaystyle M_{24 \times 16}$ tal que $D(X)$ es la suma de valores absolutos de $MV$. El $24$ surge porque hay $24$ pares de vecinos a revisar.

Asimismo, supongamos que la distribución de $X$, $\pi(X)$, es proporcional a

$$
\pi(X) \propto p^{N(X)} (1 - p)^{16 - N(X)} \exp \left( -\lambda D(X) \right).
$$

Si $\lambda = 0$, las variables son independientes e idénticamente distribuidas $\text{Bernoulli}(p)$.

Hay $2^{16}$ posibles estados, uno por cada valor posible de $X$. Usaremos el método Metropolis-Hastings con los siguientes kérneles de transición:

a) Sea $q_1$ tal que cada transición es igualmente plausible con probabilidad $1/2^{16}$. Es decir, el siguiente estado candidato para $X$ es un vector de $16$ $\text{Bernoulli}(p)$ iid.

b) Sea $q_2$ tal que se elige una de las 16 entradas en $X$ con probabilidad $1/16$, y luego se determina el valor de la celda a ser $0$ o $1$ con probabilidad $0.5$ en cada caso. Entonces, a lo más puede cambiar un solo elemento de $X$ en cada transición.

Ambas $q_1$ y $q_2$ son simétricas, irreducibles y tienen diagonales positivas. Es fácil ver que la primera se mueve más rápido que la segunda.

Estamos interesados en la probabilidad de que todos los elementos de la diagonal sean $1$. Al usar $q_1$ y $q_2$, estimaremos dicha probabilidad para los valores $\lambda \in \{0, 1, 3\}$ y $p \in \{0.5, 0.8\}$.

# Problema 2

Queremos investigar el desempeño del algoritmo de Metropolis-Hastings usando una caminata aleatoria cuando la distribución objetivo es una mezcla de dos densidades normales bivariadas para $\theta = (\theta_1, \theta_2)$

$$
\pi(\theta) = 0.7 \mathscr{N} (\theta \mid \mu_1,\ \Sigma_1) + 0.3 \mathscr{N} (\theta \mid \mu_2,\ \Sigma_2)
$$

donde

$$
\mu_1 =
\begin{pmatrix}
4 \\
5
\end{pmatrix},\
\mu_2 =
\begin{pmatrix}
0.7 \\
3.5
\end{pmatrix},\
\Sigma_1 =
\begin{pmatrix}
1   & 0.7 \\
0.7 & 1
\end{pmatrix},\
\Sigma_2 =
\begin{pmatrix}
1    & -0.7 \\
-0.7 & 1
\end{pmatrix}
$$

Supongamos que no podemos muestrear $\pi$ directamente y, en su lugar, usamos Metropolis-Hastings con $\displaystyle q(y \mid x) = \mathscr{N}(y \mid x, v I_2)$ donde $v$ es un parámetro de ajuste.

# Problema 3

Sea $\displaystyle \theta = \int_0^{\pi/3} \sin(t)dt$, usaremos Monte Carlo crudo para calcular un estimador $\hat{\theta}$.

## Variables de control

## Variables antitéticas

# Problema 4

Dados los siguientes números normales con $\mu = 3$ y $\sigma = 1$

$$
4.59,\ 4.153,\ 2.46,\ 2.732,\ 2.973;
$$

la función de distribución empírica $F_n(x)$ está dada por:

Asimismo,

$$
\begin{align}
P(F_n(3) \leq 2/5) &= a
\end{align}
$$
